### ISSUE TITLE
java.io.IOException: Could not start process: <EOF>

### ISSUE THREAD

**Issue by sagrawal31** [grails-plugins/grails-embedded-mongodb#31]
## Description

The plugin is working fine locally but when running on a CI (Gitlab's), it is failing with the following exception-

```
Caused by: java.lang.reflect.UndeclaredThrowableException
	at org.springframework.util.ReflectionUtils.rethrowRuntimeException(ReflectionUtils.java:147)
	at org.springframework.boot.SpringApplication.handleRunFailure(SpringApplication.java:798)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:318)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:99)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:132)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:141)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:90)
	... 55 more
Caused by: java.io.IOException: Could not start process: <EOF>
	at de.flapdoodle.embed.mongo.AbstractMongoProcess.onAfterProcessStart(AbstractMongoProcess.java:79)
	at de.flapdoodle.embed.process.runtime.AbstractProcess.<init>(AbstractProcess.java:116)
	at de.flapdoodle.embed.mongo.AbstractMongoProcess.<init>(AbstractMongoProcess.java:53)
	at de.flapdoodle.embed.mongo.MongodProcess.<init>(MongodProcess.java:50)
	at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:44)
	at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:34)
	at de.flapdoodle.embed.process.runtime.Executable.start(Executable.java:108)
	at org.grails.plugin.embedded.mongodb.EmbeddedMongoDBGrailsPlugin.doWithSpring_closure1(EmbeddedMongoDBGrailsPlugin.groovy:60)
```

I tried to do some googling and debugging around with no luck. Saw a matching issue as well https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/232 which seems already resolved.

## Environment

![image](https://user-images.githubusercontent.com/1804514/210039987-6ec884cd-3aaf-430c-80ed-46560e02f491.png)

**Comment by michaelmosmann** [comment]
hope this will solved with https://github.com/grails/grails-embedded-mongodb/pull/32
